### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by niallobrien** [netanelgilad/meteor-angular2#3]
Would it be possible to get some documentation? Thanks.

**Comment by yanickrochon** [comment]
+1 I have no idea how to use this. I have been watching angular2 videos, but they are not only outdated (as the project evolves quite fast), but they assume you are manually doing everything. Which is not true with Meteor.

**Comment by cesarve77** [comment]
Docs: http://angular-meteor.com/tutorials/angular2/bootstrapping
But is outdated

**Comment by netanelgilad** [comment]
Hey guys,
The docs in the site have been updated and are now using this package: https://github.com/Urigo/Meteor-Angular2. Have fun!
